# Generated by Django 4.0.6 on 2024-11-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('sigla_turno', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], default='M', max_length=15)),
                ('sigla_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.turno')),
            ],
        ),
    ]
