# Generated by Django 4.0.6 on 2024-11-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('cidade', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], default='M', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoGestao',
            fields=[
                ('regiao_gestao', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('sigla_turno', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('nome_unidade', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade_unidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacaoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('TR', 'TRABALHADO'), ('FO', 'FOLGA'), ('FS', 'FOLGA SAÚDE'), ('DO', 'DOBRA'), ('BH', 'BANCO DE HORAS'), ('FE', 'FERIAS')], max_length=15)),
                ('inicio_evento', models.DateTimeField()),
                ('fim_evento', models.DateTimeField()),
                ('status_do_evento', models.CharField(choices=[('PD', 'PENDENTE'), ('CO', 'CONFIRMADO')], default='PD', max_length=30)),
                ('nome_completo_prog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.funcionario')),
                ('sigla_turno_prog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.turno')),
                ('unidade_prog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.unidades')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sigla_turno_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.turno'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.unidades'),
        ),
        migrations.AddField(
            model_name='cidades',
            name='regiao_gestao_cidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.regiaogestao'),
        ),
    ]
